moha/asset/views.py
# -*- coding: utf-8 -*-
"""Asset views."""

from flask import Blueprint, render_template, request, flash, url_for, redirect, send_from_directory, jsonify

import forms
import models as am
from moha.facility import models as fm
from moha.structure import models as sm

from moha import utils
import moha.cache_utils as cacheDel
from moha.extensions import login_required, cache
from flask_paginate import Pagination, get_page_parameter, get_per_page_parameter
from sqlalchemy import or_

from flask import current_app as app

import structlog
logger = structlog.getLogger(__name__)

blueprint = Blueprint('asset', __name__, url_prefix='/asset', static_folder='../static')


# ============= # 
#  C H A R T S  #
# ============= #
@blueprint.route('/charts')
def _charts():
	return []

# ============= #
#  A S S E T S  #
# ============= #

#  S E A R C H 
#------------
@blueprint.route('/search')
def search():
	logger.debug('Enter assets search')
	form = forms.AssetSearchForm()
	# Create the base query for the facilities
	query = am.AssetInfo.query.order_by(am.AssetInfo.id)
	# Create base queries for different select inputs of search page
	category_query = am.AssetCategoryInfo.query.order_by(am.AssetCategoryInfo.type)
	# Collect the argumetns from the Form's GET submit and set defaults
	try:
		vNum = request.args.get('vNum')
		form.vNum.default = vNum
		if vNum:
			query = query.filter(am.AssetInfo.vNum.contains(vNum))
	except TypeError:
		pass
	try:
		# Set defaults on form so that between page refreshes the selected variables remain
		categoryID = int(request.args.get('categoryID'))
		form.categoryID.default = categoryID
		if categoryID >= 0:
			category = am.AssetCategoryInfo.query.filter_by(categoryID=categoryID).first()
			query = query.filter(am.AssetInfo.id.in_(category.asset_ids))  # checks for all assets that are of the searched category or one of the child categories  # TODO maybe faster with category_ids
	except TypeError:
		pass  # user has not yet filtered so above int() fails
	try:
		status = int(request.args.get('status'))
		form.status.default = status
		if status >= 0:
			status = True if status == 1 else False
			query = query.filter_by(status=status)
	except TypeError:
		pass
	try:
		facilityID = request.args.get('facilityID')
		form.facilityID.default = facilityID
		if facilityID:
			# Searches for matches in both facilityID and facilityName
			query = query.join(am.FunctionalAreaLocationRef).join(sm.StructureInfo).join(fm.FacilityInfo).filter(or_(fm.FacilityInfo.facilityID.contains(facilityID), fm.FacilityInfo.facilityName.contains(facilityID)))
	except TypeError:
		pass

	# Finalize the queries and add an 'all' option to the SelectFields in the form
	form.categoryID.choices = [(-1,'all')] + [(t.categoryID, t.type.strip()) for t in category_query.all()]
	form.process()  # We have to call this to 're-build' the form with our new choices and defaults selected

	# Set up pagination
	page = request.args.get(get_page_parameter(), type=int, default=1)
	per_page = request.args.get(get_per_page_parameter(), type=int, default=10)
	pagination = Pagination(page=page, per_page=per_page, total=query.count(), search=False, record_name='assets', bs_version=3)
	assets = query.limit(per_page).offset((pagination.page - 1) * per_page)
	return render_template('assets/index.html', form=form, assets=assets, pagination=pagination)

#  V I E W
#--------
@blueprint.route('/<int:assetID>')
@login_required
def view_asset(assetID):
	asset = am.AssetInfo.query.filter_by(id=assetID).first_or_404()
	return render_template('assets/asset.html', asset=asset)

def _facility_locations(facilityID):
	return [(location.id, location) for location in am.FunctionalAreaLocationRef.query.filter(am.FunctionalAreaLocationRef.structureID.in_([s.id for s in sm.StructureInfo.query.filter_by(facilityID=facilityID).all()])).all()]

#  A D D
#------
@blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add_asset():
	"""Adds an Asset."""
	logger.debug('Enter add asset')
	form = forms.AssetForm()
	form.categoryID.choices = [(c.categoryID, c.type) for c in am.AssetCategoryInfo.query.order_by(am.AssetCategoryInfo.type).all()]
	# Collect two variables which may be in the request object
	facilityID = request.args.get('facilityID')
	locationID = request.args.get('locationID')
	if locationID:
		# If locationID exists it means we already know where the asset is to be assigned
		# We can remove the locationID field from the form so that the user can not select a different location
		del form.locationID  # we will take this locationID and plug it into the database directly
	elif facilityID:
		# If facilityID exists it means we know that the user will select from a location available at this facilityID
		# This single line gathers the locationID of all locations available in this facilityID
		form.locationID.choices = _facility_locations(facilityID)
	else:
		logger.error('Missing variables from request')
		flash('Some how you found an error, if you see this message again please try a performing a different task', 'info')
		pass  # catch this

	if form.validate_on_submit():
		logger.debug('Form validated')
		# If locationID is not defined from the request then locationID will come from the form
		if not locationID:
			locationID = form.locationID.data
		newAsset = am.AssetInfo.create(categoryID=form.categoryID.data,
							status=form.status.data,
							note=form.note.data,
							manufacturer=form.manufacturer.data,
							model=form.model.data,
							supplier=form.supplier.data,
							height=form.height.data,
							width=form.width.data,
							depth=form.depth.data,
							units=form.units.data,
							datePurchased=form.datePurchased.data,
							cost=form.cost.data,
							BMENum=form.BMENum.data,
							serialNum=form.serialNum.data,
							vNum=form.vNum.data,
							locationID=locationID)
		logger.info('Created assetID: {0}'.format(newAsset.id), asset=newAsset, action='create')
		cacheDel.force_update_asset_cache()
		flash('Asset Added', 'success')
		return form.redirect(request.args.get('next'))
	else:
		utils.flash_errors(form)
	return render_template('form.html', form=form, title='Add Asset')

#  U P D A T E
#------------
@blueprint.route('/<int:assetID>/update', methods=['GET', 'POST'])
@login_required
def update_asset(assetID):
	"""Updates an asset."""
	logger.debug('Enter update assetID: {0}'.format(assetID))
	asset = am.AssetInfo.query.filter_by(id=assetID).first_or_404()
	form = forms.AssetForm(obj=asset)
	form.categoryID.choices = [(c.categoryID, c.type) for c in am.AssetCategoryInfo.query.order_by(am.AssetCategoryInfo.type).all()]
	form.locationID.choices = _facility_locations(asset.location.structure.facility.facilityID)
	if form.validate_on_submit():
		logger.debug('Form validated with assetID: {0}'.format(assetID))
		am.AssetInfo.update(asset,
							categoryID=form.categoryID.data,
							status=form.status.data,
							note=form.note.data,
							manufacturer=form.manufacturer.data,
							model=form.model.data,
							supplier=form.supplier.data,
							height=form.height.data,
							width=form.width.data,
							depth=form.depth.data,
							units=form.units.data,
							datePurchased=form.datePurchased.data,
							cost=form.cost.data,
							BMENum=form.BMENum.data,
							serialNum=form.serialNum.data,
							vNum=form.vNum.data,
							locationID=form.locationID.data)
		logger.info('Updated assetID: {0}'.format(assetID), asset=asset, action='update')
		cacheDel.force_update_asset_cache()
		flash('Asset Updated', 'success')
		return form.redirect(request.args.get('next'))
	else:
		utils.flash_errors(form)
	return render_template('form.html', form=form, title='Update Asset')

#  D E L E T E 
#------------
@blueprint.route('/<int:assetID>/delete')
@login_required
def delete_asset(assetID):
	"""Removes an asset from the database."""
	logger.debug('Enter delete assetID: {0}'.format(assetID))
	form = forms.AssetForm()
	asset = am.AssetInfo.query.filter_by(id=assetID).first_or_404()
	am.AssetInfo.delete(asset)
	logger.info('Removed assetID: {0}'.format(assetID), asset=asset, action='delete')
	cacheDel.force_update_asset_cache()
	flash('Asset Deleted', 'success')
	return form.redirect(request.args.get('next'))
		
# ================= #
#  L O C A T I O N  #
# ================= #

#  A D D 
#------
@blueprint.route('/location/add', methods=['GET', 'POST'])
@login_required
def add_location():
	"""Add a functional area to a structure."""
	logger.debug('Enter add location')
	facilityID = request.args.get('facilityID')
	structureID = request.args.get('structureID')
	form = forms.LocationForm()
	form.functionalAreaID.choices = [(fa.id, fa.identifier) for fa in am.FunctionalAreaRef.query.all()]
	if structureID:
		del form.structureID
	else:
		form.structureID.choices = [(s.id, s.identifier) for s in sm.StructureInfo.query.filter_by(facilityID=facilityID).all()]
	if form.validate_on_submit():
		logger.debug('Form validated')
		if not structureID:
			structureID = form.structureID.data
		location = am.FunctionalAreaLocationRef.create(structureID=structureID, functionalAreaID=form.functionalAreaID.data)
		logger.info('Created locationID: {0}'.format(location.id), location=location, action='create')
		cacheDel.force_update_asset_cache()
		flash('Asset location added', 'success')
		return form.redirect(request.args.get('next'))
	else:
		utils.flash_errors(form)
	return render_template('form.html', form=form, title='Add Asset Location')


#  U P D A T E
#------------
@blueprint.route('/location/<int:locationID>/update', methods=['GET', 'POST'])
@login_required
def update_location(locationID):
	logger.debug('Enter update locationID: {0}'.format(locationID))
	facilityID = request.args.get('facilityID')
	location = am.FunctionalAreaLocationRef.query.filter_by(id=locationID).one()
	form = forms.TransferForm()
	form.structureID.choices = [(s.id, s.identifier) for s in sm.StructureInfo.query.filter_by(facilityID=facilityID).all()]

moha/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import current_app as app
from flask import Blueprint, render_template, redirect, flash, request, url_for, flash
from flask_login import login_required, login_user

from moha.user.forms import RegisterForm
from moha.user.models import User
from moha.extensions import Message, mail
from moha.utils import flash_errors

from itsdangerous import URLSafeTimedSerializer
from datetime import datetime

import logging
logger = logging.getLogger('moha.user.views')

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
	"""List members."""
	return render_template('users/members.html')


def generate_confirmation_token(email):
	serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
	return serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])

def confirm_token(token, expiration=3600):
	serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
	try:
		email = serializer.loads(token, salt=app.config['SECURITY_PASSWORD_SALT'], max_age=expiration)
	except:
		return False
	return email


@blueprint.route('/register/', methods=['GET', 'POST'])
def register():
	"""Register new user.

	A user will register with a proper vanuatu.gov.vu email account, then the 
	user must be confirmed by a current user of MOHA from the admin panel.
	"""
	logger.debug('Enter register new user')
	form = RegisterForm(request.form, csrf_enabled=False)
	if form.validate_on_submit():
		logger.debug('Form validated')
		newUser=User.create(username=form.email.data, 
							email=form.email.data, 
							password=form.password.data, 
							first_name=form.first_name.data, 
							last_name=form.last_name.data,
							confirmed=True,
							active=True)
		logger.info('New User Created: {0} - {1}'.format(newUser.full_name, newUser.email))
		# User is not auto logged in after restering. A current user must approve of their access.
		#login_user(newUser)
		#logger.info('Logged in: {0}'.format(newUser.username))
		flash('Welcome, {0}'.format(newUser.full_name), 'success')
		flash('Please manage the data here responsibly, you can edit or delete anything.', 'info')
		return redirect(url_for('public.home'))
	else:
		flash_errors(form)
	return render_template('public/register.html', form=form)


"""
@blueprint.route('/confirm/<token>')
def confirm_email(token):
	try:
		email = confirm_token(token)
	except:
		flash('The confirmation link is invalid or has expired.', 'danger')
	user = User.query.filter_by(email=email).first_or_404()
	if user.confirmed:
		flash('Account already confirmed. Please login.', 'success')
	else:
		user.confirmed = True
		user.confirmed_on = datetime.now()
		User.update(user, confirmed=True, confirmed_on=datetime.now()) # Not needed with my CRUDMixim #.filter_by(email=email).first_or_404()
		flash('You have confirmed your account. Thanks!', 'success')
	return redirect(url_for('public.home'))



def send_email(to, subject, template):
	msg = Message(subject=subject, recipients=[to], sender=app.config['MAIL_DEFAULT_SENDER'])
	msg.html = template
	with app.app_context():
		mail.send(msg)
"""

moha/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('user.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

moha/templates/csrf_error.html
{% extends "layout.html" %}

{% block page_title %}CSRF Error{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1><i class="fa fa-exclamation-triangle"></i> CSRF Error</h1>
        <h2><small>This means the form has expired.</small></h2>
        <p><strong>You did nothing wrong.</strong> After a certain amount of time the form becomes invalid for security reasons. Go ahead and return to the form you were working on and everything will be okay.</p>

        <p>Next time try not to leave for lunch before you submit the form.</p>
    </div>
</div>
{% endblock %}

moha/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Michael Toohig</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:mtoohig@vanuatu.gov.vu">Contact</a></li>
    </ul>
  </small>
</footer>

moha/templates/form.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_datefield %}
    <form id="registerForm" class="form form-register" method="POST" action="" role="form" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>        

            {% for field in form %}
                {% if field.label.text == "CSRF Token" %}
                    {{ field }}
                
                {% elif field.widget.input_type == "hidden" %}
                    {{ field(class_="form-control") }}
                
                {% elif field.type == 'DateField' %}
                    {{ render_datefield(field) }}

                {% elif field.label.text == 'Status' %}
                    <div class="form-group">
                        {{ field.label }}
                        <br/>
                        <input {{ 'checked' if field.data == True else '' }} id="status" type="checkbox" data-toggle="toggle" data-on="Operational" data-off="Non-Operational" data-width="180" name="status" value="y"/>
                        <p class="help-block">{{ field.description }}</p>
                    </div>
                
                {% elif field.type == 'RadioField' %}
                    <div class='form-group'> 
                        {{ field.label }}
                        <br/>
                        <div class='btn-group' data-toggle='buttons'>
                            {% for r in field %}
                            <label class="btn btn-default {{ 'active' if r.checked else '' }}">
                                {{ r(type="radio")|safe }} {{ r.label }}
                            </label>
                            {% endfor %}
                        </div> 
                    </div>

                {% else %}
                    {{ render_field(field) }}
                {% endif %}
            {% else %}
                Error loading form. Please contact Application Administrator @ OGCIO
            {% endfor %}

            <p><input class="btn btn-primary btn-lg btn-submit btn-block" id="upload-button" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <title>{% block page_title %}MOHA{% endblock %}</title>

  <!-- Mobile viewport optimized: h5bp.com/viewport -->

{% assets "css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
{% endassets %}

{% block css %}{# page-specific CSS #}{% endblock %}

{% assets "js_head" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% block head_script %}{# defer-incapable JS block #}{% endblock %}

</head>
<body class="{% block body_class %}body-sidebar{% endblock %}">
{% block body %}
<div class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm">
  <a class="navmenu-brand visible-md visible-lg" href="{{ url_for('public.home') }}">MOHA</a>
  <ul class="nav navmenu-nav">
  {% if current_user and current_user.is_authenticated %}
    <!-- <li><a class="navmenu-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i> Log out</a></li> -->
  {% elif not current_user.is_authenticated and loginForm %}
    <li><a data-toggle="modal" href="#LoginModal"><i class="fa fa-sign-in"></i> Login</a></li>
  {% endif %}
    <li style="background-color:gray;height:2px;width:90%;position:center;display:block;border-radius: 4px;margin:2%;"></li>
  </ul>
  <ul class="nav navmenu-nav" id="jazny-sidebar">
    {% block sidenav %}
    <li><a href="{{ url_for('facility.search') }}" class="navmenu-link"><i class="fa fa-hospital-o"></i> Facilities</a></li>
    <li><a href="{{ url_for('structure.search') }}" class="navmenu-link"><i class="fa fa-home"></i> Structures and Fleet Assets</a></li>
    <li><a href="{{ url_for('asset.search') }}"><i class="fa fa-medkit"></i> Assets</a></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user-md"></i> Human Resources <b class="caret"></b></a>
      <ul class="dropdown-menu navmenu-nav">
        <li><a href="{{ url_for('personnel.search') }}">All</a></li>
        <li><a href="{{ url_for('personnel.sort_cadre') }}">By Cadre</a></li>
      </ul>
    </li>
    <li style="background-color:gray;height:2px;width:90%;position:center;display:block;border-radius: 4px;margin:2%;"></li>
    {% endblock %}
  </ul>
  <div style="margin: 10px;">
    {% block sidebar %}{% endblock %}
  </div>
</div>

<div class="navbar navbar-default navbar-fixed-top hidden-md hidden-lg">
  <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="{{ url_for('public.home') }}">Assets Unit Webapp</a>
</div>

{% if not current_user.is_authenticated and loginForm %}
<!-- Login Modal -->
<div class="modal fade" tabindex="-1" id="LoginModal">
  <div class="modal-dialog modal-sm"> 
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">x</button>
        <h3>Login</h3>
      </div>
      <div class="modal-body">
        <form id="loginForm" method="POST" class="" role="login">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          {{ loginForm.next }}
          <div class="form-group">
            {{ loginForm.email(placeholder="Email", class_="form-control") }}
          </div>
          <div class="form-group">
            {{ loginForm.password(placeholder="Password", class_="form-control") }}
          </div>
          <button type="submit" class="btn btn-default">Log in</button>
        </form>
      </div>
      <div class="modal-footer">
        First time here? 
        <a href="{{ url_for('user.register') }}" class="btn btn-primary">Create account</a>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% block outer_content %}
<div class="container">
  <div class="content">
  {% block content %}{% endblock %}
  </div>
</div><!-- /.container -->
{% endblock %}

<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

{# include "footer.html" #}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

{% block js %}{# defer-capable JS block #}{% endblock %}

<!-- Extra Scripts for plugins used across the app -->
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
  $('[data-toggle="confirmation"]').confirmation({});
});
</script>
<!-- Notify for flashed messages -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <script>
      $(function() {
        $.notify({
            message: "{{ message }}"
          },{
            type: '{{ category }}',
            animate :{
              enter: 'animated fadeInUp',
              exit: 'animated fadeOutUp'
            },
            placement: {
              from: 'bottom',
              align: 'right'
            },
            offset: 20,
            spacing: 10,
            z_index: 1031,
            delay: 4500
          })
      }); 
      </script>
    {% endfor %}
  {% endif %}
{% endwith %}

<!-- end scripts -->
{% endblock %}

</body>
</html>

moha/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <button type="button" class="navbar-toggle visible-xs pull-left" data-toggle="offcanvas">
      <span class="sr-only">Toggle sidebar</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">Asset Unit Webapp</a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('facility.search') }}">Facilities</a></li>
      <li><a href="{{ url_for('public.map') }}">Map</a></li>
      <li><a href="{{ url_for('public.assets') }}">Assets</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.full_name }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i> Log out</a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <!-- Trigger the modal with a button -->
      <li><a href="{{ url_for('user.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="form-group">
        {{ form.email(placeholder="Email", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->

  </div><!-- /.container -->
</nav>