moha/facility/forms.py
# -*- coding: utf-8 -*-
"""Facility forms."""
import datetime

from flask_wtf import Form
from wtforms import StringField, SelectField, FloatField, DateField, FileField, TextAreaField, BooleanField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange

import models as fm


class StarfishForm(Form):
	"""Edit Facility."""

	directory = SelectField('Directory', choices=[])

	def __init__(self, *args, **kwargs):
		"""Create instance."""
		super(StarfishForm, self).__init__(*args, **kwargs)
		self.starfish = None

	def validate(self):
		"""Validate the form."""
		initial_validation = super(StarfishForm, self).validate()
		if not initial_validation:
			return False
		
		return True


class FacilityFileForm(Form):
	"""Add File to Facility"""

	file = FileField('Picture/File', render_kw={'multiple': 'multiple'}, validators=[DataRequired()],
								description='Select multiple files at once using the `CTRL` key to load them all together.')

	description = StringField('Desciption',
								render_kw={'placeholder': 'Description of Picture/File'},
								validators=[Length(min=0, max=500, message='File description may not exceed 500 characters.')])

	dateCreated = DateField('Date of Picture/File',
								default=datetime.datetime.now().date(),
								validators=[DataRequired()],
								format="%d/%m/%Y")

	def __init__(self, *args, **kwargs):
		"""Create instance."""
		super(FacilityFileForm, self).__init__(*args, **kwargs)
		self.FacilityFileForm = None

	def validate(self):
		"""Validate the form."""
		initial_validation = super(FacilityFileForm, self).validate()
		if not initial_validation:
			return False

		return True


class FacilityNoteForm(Form):
	"""Add a Note to Facility"""

	note = TextAreaField('Note', render_kw={'placeholder': 'Type your note here.'},
								validators=[DataRequired(message="You didn't write anything!"), Length(max=2000, message="May not exceed 2000 characters")])

	def __init__(self, *args, **kwargs):
		"""Create instance."""
		super(FacilityNoteForm, self).__init__(*args, **kwargs)
		self.FacilityNoteForm = None

	def validate(self):
		"""Validate the form."""
		initial_validation = super(FacilityNoteForm, self).validate()
		if not initial_validation:
			return False

		return True


class FacilitySearchForm(Form):
	"""Search Facility List"""

	facilityName = StringField('Facility Name')

	designation = SelectField('Designation', choices=[], coerce=int)

	province = SelectField('Province', choices=[], coerce=int)

	healthZone = SelectField('Health Zone', choices=[])

	island = SelectField('Island', choices=[], coerce=int)

	def validate(self):
		"""Validate the form."""
		initial_validation = super(FacilitySearchForm, self).validate()
		if not initial_validation:
			return False

		return True


class FacilityForm(Form):
	"""Edit Facility."""

	facilityID = StringField('Facility ID',
								render_kw={"placeholder": "Facility ID"},
								validators=[DataRequired()])

	facilityName = StringField('Facility Name',
								render_kw={"placeholder": "Facility Name"},
								validators=[DataRequired()])

	altFacilityName = StringField('Local Facility Name',
								render_kw={"placeholder": "Local Facility Name"})

	dataSource = StringField('Data Source', 
								render_kw={"placeholder": "Data Source"})

	designationID = SelectField('Designation', 
								choices=[], 
								coerce=int,
								render_kw={"placeholder": "Designation"},
								validators=[DataRequired()], )

	provinceID = SelectField('Province', 
								choices=[],
								coerce=int,
								render_kw={"placeholder": "Province"},
								validators=[DataRequired()])

	islandID = SelectField('Island', 
								choices=[],
								coerce=int,
								render_kw={"placeholder": "Island"},
								validators=[])#RequiredIf('healthZone')])

	healthZoneID = SelectField('Health Zone', 
								choices=[],
								coerce=int,
								render_kw={"placeholder": "Health Zone"},
								validators=[])#RequiredIf('islandID')])

	areaCouncilID = SelectField('Area Council',
								choices=[],
								coerce=int,
								render_kw={"placeholder": "Area Council"},
								validators=[DataRequired()])
	
	longD = IntegerField('Degrees')
	
	longM = IntegerField('Minutes', 
								validators=[NumberRange(min=0, max=59, message="Must be between 0 and 59")])
	
	longS = FloatField('Seconds')

	latD = IntegerField('Degrees')
	
	latM = IntegerField('Minutes', 
								validators=[NumberRange(min=0, max=59, message="Must be between 0 and 59")])
	
	latS = FloatField('Seconds')

	ownershipID = SelectField('Ownership', 
								choices=[], 
								coerce=int,
								render_kw={"placeholder": "Onwership"},
								validators=[DataRequired()])

	settingID = SelectField('Setting', 
								choices=[], 
								coerce=int,
								render_kw={"placeholder": "Setting"},
								validators=[DataRequired()])

	status = BooleanField('Status', default=True, description="Is the facility Open?")
								
	landOwner = StringField('Land Owner',
								render_kw={"placeholder": "Land Owner"})

	landOwnerContact = StringField('Land Owner Contact',
								render_kw={"placeholder": "Land Owner Contact"})

	landTitle = StringField('Land Title',
								render_kw={"placeholder": "Land Title"})

	manager = StringField('Facility Manager',
								render_kw={"placeholder": "Facility Manager"})

	managerContact = StringField('Manager Contact',
								render_kw={"placeholder": "Manager Contact"})

	def __init__(self, *args, **kwargs):
		"""Create instance."""
		super(FacilityForm, self).__init__(*args, **kwargs)
		self.facility = None

	def validate(self):
		"""Validate the form."""
		initial_validation = super(FacilityForm, self).validate()
		if not initial_validation:
			return False

		if self.latD.data < 13:
			self.latD.errors.append('There are no islands that far north')
			return False

		if self.latD.data > 22:
			self.latD.errors.append('There are no islands that far south')
			return False

		if self.longD.data < 166:
			self.longD.errors.append('There are no islands that far east')
			return False

		if self.longD.data > 171:
			self.longD.errors.append('There are no islands that far west')
			return False

		if self.latS.data < 0 or self.latS.data > 60:
			self.latS.errors.append('must be between 0 and 60')
			return False

		if self.longS.data < 0 or self.longS.data > 60:
			self.latS.errors.append('must be between 0 and 60')
			return False

		return True

moha/facility/__init__.py
# -*- coding: utf-8 -*-
"""The facility module."""
from . import views  # noqa

moha/facility/views.py
# -*- coding: utf-8 -*-
"""Facility views"""
import os
import datetime
import pygal

from flask import Blueprint, render_template, request, flash, url_for, redirect, send_from_directory, jsonify, current_app
from flask import current_app as app
from flask_login import login_required, current_user
from flask_paginate import Pagination, get_page_parameter, get_per_page_parameter

from moha.extensions import csrf_protect, cache

import forms
import models as fm
import business as bus
from moha import utils
import moha.cache_utils as cacheDel

from sqlalchemy import or_

from moha.asset import models as am
from moha.personnel import models as pm
from moha.structure import models as sm

import structlog
logger = structlog.getLogger(__name__)

blueprint = Blueprint('facility', __name__, url_prefix='/facility', static_folder='../static')

# ============= #
#  C H A R T S  #
# ============= #
"""This section contains charts and graphs related to facilities.

They are called from the _charts() function via its route.
This will be a jQuery call that requests the charts to be created and sent to the browser.
This is because these graphs are relatively resource intensive to create and would
slow down the browser too much when loading the page.

Charts themselves are made with PyGal which you can learn about here: http://pygal.org/en/stable/
They are quite simple to create and have good aesthetic quality in my opinion. They come included
with a minimal javascipt component that makes them somewhat interactive. The charts are svg 
which means they will scale to any size and can be imported into other documents.

Each chart appears to be made in 10 lines of code or less but that is not true. 
The charts *Heavily* use SQLAlchemy hybrid_method and hybrid_property functions to help build the 
lists required to populate the chart. In the models you can find these hybrid_property and 
hybrid_method functions that are doing the work to build the data for the charts. These
functions can follow relationships between models and therefore can travel many models before 
returning with the data for the chart. But following the functions will show you how a 
chart gathers its data and you will have no problem debugging it.

Lastly, the actual charts are shown on screen with jQuery (as mentioned above), so the 
code that calls for these functions will be found in the templates. The return 
statements are dictionaries so that they can be encoded into JSON for jQuery.
"""

#  S E A R C H 
#------------
@cache.memoize(timeout=300)
def _chart_designation_by_province(disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	designations = fm.DesignationRef.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Designations by Province'
	chart.x_labels = [p.name for p in provinces]
	for d in designations:
		chart.add(d.name, [d.total_designations(p.id) for p in provinces])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@cache.memoize(timeout=300)
def _chart_percent_designation_by_province(disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	designations = fm.DesignationRef.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Designations by Province (%)'
	chart.value_formatter = lambda x: '{}%'.format(x)
	chart.x_labels = [p.name for p in provinces]
	for d in designations:
		chart.add(d.name, [(d.total_designations(p.id)/float(p.total_facilities))*100 if p.total_facilities > 0 else None for p in provinces])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@cache.memoize(timeout=300)
def _chart_facility_condition(disable_xml_declaration=False):
	facilities = fm.FacilityInfo.query.all()
	chart = pygal.Pie(style=pygal.style.BlueStyle)
	chart.title = 'Facility Status'
	chart.show_legend = False
	chart.add('Status', [{'value': len([f for f in facilities if f.status and not f.damaged]), 'label': 'Open', 'color': 'green'},
						{'value': len([f for f in facilities if not f.status and not f.damaged]), 'label': 'Closed', 'color': 'black'},
						{'value': len([f for f in facilities if f.status and f.damaged]), 'label': 'Open/Damaged', 'color': 'orange'},
						{'value': len([f for f in facilities if not f.status and f.damaged]), 'label': 'Closed/Damaged', 'color': 'red'}])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@cache.memoize(timeout=300)
def _chart_percent_facility_condition_by_province(disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Facility Status by Province (%)'
	chart.value_formatter = lambda x: '{}%'.format(x)
	chart.show_legend = False
	chart.x_labels = [p.name for p in provinces]
	chart.add('', [{'value': p.facilities_open/float(len(p.facilities))*100, 'label': 'Open', 'color': 'green'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_closed/float(len(p.facilities))*100, 'label': 'Closed', 'color': 'black'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_damaged_open/float(len(p.facilities))*100, 'label': 'Damaged/Open', 'color': 'orange'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_damaged_closed/float(len(p.facilities))*100, 'label': 'Damaged/Closed', 'color': 'red'} if p.total_facilities > 0 else None for p in provinces])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@cache.memoize(timeout=300)
def _chart_facility_rank():
	"""This is a test and not a complete ranking or report"""
	provinces = fm.ProvinceInfo.query.all()
	facilities = fm.FacilityInfo.query.all()
	chart = pygal.XY(style=pygal.style.BlueStyle)
	chart.stroke = False
	chart.title = 'Facility Condition'
	for f in facilities:
		chart.add(f.facilityName, [])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@blueprint.route('/data/charts')
def _charts():
	logger.debug('Enter _charts')
	chart1 = _chart_designation_by_province()
	chart2 = _chart_percent_designation_by_province()
	chart3 = _chart_facility_condition()
	chart4 = _chart_percent_facility_condition_by_province()
	chart5 = _chart_facility_rank()
	logger.debug('Exit _charts')
	return jsonify({'charts': [chart1, chart2, chart3, chart4, chart5]})


# ===================== #
#  F A C I L I T I E S  #
# ===================== #

#  S E A R C H 
#------------
@blueprint.route('/search/')
@csrf_protect.exempt
def search():
	"""List Facilities."""
	logger.debug('Enter facility search')
	form = forms.FacilitySearchForm()
	# Create the base query for the facilities
	query = fm.FacilityInfo.query.order_by(fm.FacilityInfo.facilityName)
	# Create base queries for different columns of search page
	province_query = fm.ProvinceInfo.query.order_by(fm.ProvinceInfo.id)
	island_query = fm.IslandInfo.query.order_by(fm.IslandInfo.name)
	healthZone_query = fm.HealthZoneInfo.query.order_by(fm.HealthZoneInfo.name)
	designation_query = fm.DesignationRef.query.order_by(fm.DesignationRef.name)
	# Collect the argumetns from the Form's GET submit and set defaults
	try:
		# Set defaults on form so that between page refreshes the selected variables remain
		facilityName = request.args.get('facilityName')
		provinceID = int(request.args.get('province'))
		form.province.default = provinceID
		islandID = int(request.args.get('island'))
		form.island.default = islandID
		healthZoneID = request.args.get('healthZone')
		form.healthZone.default = healthZoneID
		designationID = int(request.args.get('designation'))
		form.designation.default = designationID
		if facilityName is not None:
			query = query.filter(or_(fm.FacilityInfo.facilityName.contains(facilityName), fm.FacilityInfo.altFacilityName.contains(facilityName)))
			form.facilityName.default = facilityName
		if provinceID >= 0:
			query = query.filter(fm.FacilityInfo.provinceID==provinceID)
			island_query = island_query.filter(fm.IslandInfo.provinceID==provinceID)
		if islandID >= 0:
			query = query.filter(fm.FacilityInfo.islandID==islandID)
		if healthZoneID >= 0 and healthZoneID != '-1':
			query = query.filter(fm.FacilityInfo.healthZoneID==healthZoneID)
		if designationID >= 0:
			query = query.filter(fm.FacilityInfo.designationID==designationID)
	except TypeError:
		pass  # user has not yet filtered so above int() fails

	# Finalize the queries and add an 'all' option to the SelectFields in the form
	form.province.choices = [(-1,'all')] + [(p.id, p.name.strip()) for p in province_query.all()]
	form.island.choices = [(-1,'all')] + [(i.id, i.name.strip()) for i in island_query.all()]
	form.healthZone.choices = [('-1','all')] + [(h.id, h.name.strip()) for h in healthZone_query.all()]
	form.designation.choices = [(-1,'all')] + [(d.id, d.name.strip()) for d in designation_query.all()]
	form.process()  # We have to call this to 're-build' the form with our new choices and defaults selected
	# Set up pagination
	page = request.args.get(get_page_parameter(), type=int, default=1)
	per_page = request.args.get(get_per_page_parameter(), type=int, default=10)	
	pagination = Pagination(page=page, per_page=per_page, total=query.count(), search=False, record_name='facilities', bs_version=3)
	facilities = query.limit(per_page).offset((pagination.page - 1) * per_page)
	return render_template('facilities/facilities.html', form=form, facilities=facilities, pagination=pagination)#, charts=_facility_charts())

#  V I E W
#--------
@blueprint.route('/<facilityID>')
@login_required
def facility(facilityID):
	""" Main page blo wan Facility. 
		Includes Buildings, inspections, Files, Pictures, and Data about facility."""
	logger.debug("Enter view facilityID: {0}".format(facilityID), facilityID=facilityID, action='view')
	noteForm = forms.FacilityNoteForm()
	facility = fm.FacilityInfo.query.filter_by(facilityID=facilityID).first_or_404()

moha/templates/facilities/buildings.html
{% extends "layout.html" %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){
  $("#BuildingModal").on('show.bs.modal', function(event){
        var button = $(event.relatedTarget);  // Button that triggered the modal
        var titleData = button.data('title'); // Extract value from data-* attributes
        var listData = button.data('list');
        var dd = JSON.stringify(listData);
        $(this).find('.modal-title').text(titleData);
    });
});
</script>
{% endblock %}

{% block content %}
<!-- T A B L E S -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      <div class='btn-toolbar pull-right'>
          <div class='btn-group'>
            <button class="btn btn-default {{ 'disabled' if not charts }}" data-toggle="collapse" href="#graphs"><i class="fa fa-bar-chart"></i> Graphs</button>
            <button class="btn btn-default dropdown-toggle btn-large" data-toggle="dropdown"><i class="fa fa-cogs"></i> Options <i class="fa fa-caret-down"></i></button>
            <ul class="dropdown-menu pull-right">
              <li><a href="#">Add ... nothing</a></li>
            </ul>         

          </div>
      </div>
      Buildings
    </h1>
  </div>
</div>

<div class="row collapse graphTabs" id="graphs">
  <ul class="nav nav-pills">
  {% for chart in charts %}
    <li class="{{'active' if loop.first}}"><a href="#chart-{{loop.index}}" data-toggle="tab">Chart {{loop.index}}</a></li>
  {% endfor %}
  </ul>

  <div class="tab-content clearfix">
  {% for chart in charts %}
    <div class="tab-pane {{'active' if loop.first }}" id="chart-{{loop.index}}">
      <embed style="width:100%;height:75vh;" type="image/svg+xml" src="{{ chart|safe }}"/>
    </div>
  {% endfor %}
  </div>
</div>

{% if building_type %}
<div class="row">
  <table class="table table-hover table-bordered table-stripped">
    <thead>
      <tr>
        <th>{{ building_type.type }}</th>
        {% for province in provinces %}
        <th>{{ province.name }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
    {% for designation in designations %}
      <tr>
        <td>{{ designation.name }}</td>
        {% for province in provinces %}
        <td>
          {% set buildings = designation.province_list(building_type, designation, province) %}
          {% if buildings|length > 0 %}

          <!-- M O D A L -->
          <div id="BuildingModal-{{loop.index}}" class="modal fade">
              <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                          <h4 class="modal-title">{{ building_type.type }} | {{ designation.name }} | {{ province.name }}</h4>
                      </div>
                      <div class="modal-body">
                         <table class="table table-striped table-hover table-condensed">
                          <thead>
                            <tr>
                              <th>Facility ID</th>
                              <th>Facility Name</th>
                              <th>Island</th>
                              <th>Health Zone</th>
                              <th>Status</th>
                              <th>Constuction</th>
                              <th>Area</th>
                              <th>Condition</th>
                            </tr>
                          </thead>
                          <tbody class="rowlink" data-link="row">
                            {% for building in buildings %}
                            <tr class="{{ 'danger' if not building.status }}">
                              <td><a href="{{ url_for('facility.facility', facilityID=building.facility.facilityID) }}"></a>{{ building.facility.facilityID }}</td>
                              <td>{{ building.facility.facilityName }}</td>
                              <td>{{ building.facility.island.name }}</td>
                              <td>{{ building.facility.healthZone }}</td>
                              <td>{{ 'Operational' if building.status else 'Non-Operational' }}</td>
                              <td>{{ building.construction.type }}</td>
                              <td>{{ building.area }} sqm.</td>
                              <td>{{ building.inspection.condition if building.inspection else 'No inspection yet' }}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                      </div>
                  </div>
              </div>
          </div>

          <button type="button" class="btn btn-info btn-block" style="padding:0;" data-toggle="modal" data-target="#BuildingModal-{{loop.index}}">{{ buildings|length }}/{{ designation.total_designations(province.id) }}</button>
          {% endif %}
        </td>
        {% endfor %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}

<div class="row">
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr>
        <th></th>
        {% for d in designations %}
        <th>{{ d.name }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody class="rowlink" data-link="row">
    {% for type in building_types %}
      <tr>
        <td><a href="{{ url_for('facility.buildings', building_type=type.id) }}"></a>{{ type.type }}</td>
        {% for designation in designations %}
        <td style="text-align:center;">{{ designation.type_list(type, designation)|length if designation.type_list(type, designation)|length > 0 else '' }}</td>
        {% endfor %}
      </tr>
  	{% endfor %}
    </tbody>
  </table>    
</div>
{% endblock %}

moha/templates/facilities/facilities.html
{% extends "layout.html" %}

{% block content %}
<div class="body-content">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <div class='btn-toolbar pull-right'>
            <div class='btn-group'>
              <button class="btn btn-default" data-toggle="collapse" href="#graphs"><i class="fa fa-bar-chart"></i> Graphs</button>
              <button class="btn btn-default dropdown-toggle btn-large" data-toggle="dropdown"><i class="fa fa-cogs"></i> Options <i class="fa fa-caret-down"></i></button>
              <ul class="dropdown-menu pull-right">
                <li><a href="{{ url_for('facility.add_facility') }}">Add Facility</a></li>
                <li><a href="{{ url_for('report.facilities', designationID=form.designation.default, islandID=form.island.default, healthZoneID=form.healthZone.default, provinceID=form.province.default) }}"><i class="fa fa-download"></i> Download Excel</a></li>
              </ul>     
            </div>
        </div>
        Facilities
      </h1>
    </div>
  </div>

  <script>

    $.getJSON("{{ url_for('facility._charts') }}", function(data) {
      $('#graphs').find('#chart-navigation').empty();
      $.each(data.charts, function(i, chart) {
        var $nav = $('<li>').append(
          $('<a href="#" data-toggle="tab">').text(chart.title).attr('href', '#chart-' + i)
          );
        var $chart = $('<div>', {'class': 'tab-pane', 'id': ""}).append(
          $('<embed>', {'style': "width:100%;height:75vh;", 'type': "image/svg+xml"})
          );
        var $chart = $chart.attr('id', 'chart-' + i);
        $('#graphs').find('#chart-navigation').append($nav);
        $('#graphs').find('#chart-div').append($chart);
        $('#chart-' + i).find('embed').attr('src', chart.data);
      });
      makeActive();
    });
      
    function makeActive() {
      $("#chart-navigation li:first").addClass("active");
      $("#chart-div div:first").addClass("active");
    };
  </script>

  <div class="row collapse graphTabs" id="graphs">
    <ul class="nav nav-pills" id="chart-navigation">
    </ul>

    <div class="tab-content clearfix" id="chart-div">
    </div>
  </div>

  <div class="row">
  {{ pagination.info }}
    <table class="table table-condensed">
      <thead>
        <tr style="font-size:1.4em;font-weight:700;">
          <th>#</th>
          <th>Facility ID</th>
          <th>Name</th>
          <th>Local Name</th>
          <th>Desigination</th>
          <th>Island</th>
          <th>Heath Zone</th>
          <th>Province</th>
        </tr>
        <tr>
          <form action="{{ url_for('facility.search') }}" method="GET">
            <th></th>
            <th></th>
            <th>
              <div class="form-group">
                {{ form.facilityName(class_="form-control") }}
              </div>
            </th>
            <th></th>
            <th>
              <div class="form-group">
                {{ form.designation(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.island(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.healthZone(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.province(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                <button class="btn btn-default btn-block" type="submit" value="submit"><i class="fa fa-refresh"></i></button>
              </div>
            </th>
          </form>
        </tr>
      </thead>
      <tbody class="rowlink" data-link="row">
    	{% for facility in facilities %}
        <tr class="{{ facility|colorCode }}">
          <td><a href="{{ url_for('facility.facility', facilityID=facility.facilityID) }}"></a>{{ loop.index + (pagination.page - 1) * pagination.per_page }}</td>
          <td>{{ facility.facilityID }}</td>
          <td>{{ facility.facilityName }}</td>
          <td>{{ facility.altFacilityName if facility.altFacilityName != None else '' }}</td>
          <td>{{ facility.designation.name }}</td>
          <td>{{ facility.island.name }}</td>
          <td>{{ facility.healthZone }}</td>
          <td>{{ facility.province.name }}</td>
        </tr>
    	{% endfor %}
      </tbody>
    </table>
    {{ pagination.links }} 
  </div>
</div>
{% endblock %}

moha/templates/facilities/facility_files.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
        
    <div class="well">
        <h2>{{ facility.identifier }}</h2>
        <p>Edit Available Files</p>
        <hr/>
        <p class="bg-info">Edit the description and date of photos. However, to change a photo for another one or edit the name you will need to delete the photo and re-upload it with the correct information.</p>
           
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th class="col-sm-2">Picture</th>
                    <th class="col-sm-2">File Name</th>
                    <th class="col-sm-4">File Description</th>
                    <th class="col-sm-2">Date</th>
                    <th class="col-sm-2"></th>
                </tr>
            </thead>
            <tbody>
                {% for pic in pics %} 
                {% if pic.default %}
                <tr class="bg-primary">
                {% else %}
                <tr>
                {% endif %}
                    <td>
                        <img src="{{ url_for('facility.download_file', facilityID=facility.facilityID, filename=pic.file.fileName, file_type='picture') }}" style="height: 100px; width: 100px;"/>
                    </td>
                    <td style="word-break: break-all;">{{ pic.file.fileOriginalName }}</td>
                    <td>{{ pic.file.fileDesc }}</td>
                    <td>{{ pic.file.fileDateCreated }}</td>
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-danger btn-sm" data-toggle="confirmation" data-href="{{ url_for('facility.delete_facility_file', facilityID=facility.facilityID, fileID=pic.fileID, file_type='picture') }}"><i class="fa fa-times"></i></button>
                            <a class="btn btn-default btn-sm" href="{{ url_for('facility.update_facility_file', facilityID=facility.facilityID, fileID=pic.fileID) }}">Edit</a>
                            {% if not pic.default %}
                            <a class="btn btn-default btn-sm" href="{{ url_for('facility.make_default_file', facilityID=facility.facilityID, fileID=pic.fileID, file_type='picture') }}">Make Default</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{{ url_for('facility.facility', facilityID=facility.facilityID) }}" class="btn btn-primary btn-block">Return to facility</a>
    </div>

</div>
{% endblock %}