moha/structure/__init__.py
# -*- coding: utf-8 -*-
"""The Structure module."""
from . import views  # noqa

moha/structure/views.py
# -*- coding: utf-8 -*-
"""Structure views."""
import os
import pygal

from flask import Blueprint, render_template, request, flash, url_for, redirect, g, jsonify
from flask import current_app as app
from flask_login import login_required
from flask_paginate import Pagination, get_page_parameter, get_per_page_parameter

from moha.extensions import csrf_protect, cache

import forms
import models as sm
import business as bus

from moha.facility import models as fm
from moha import utils
import moha.cache_utils as cacheDel

import structlog
logger = structlog.getLogger(__name__)

blueprint = Blueprint('structure', __name__, url_prefix='/structure', static_folder='../static')


'''
def _export_facility_network(facilityID):
	import networkx as nx
	structures = sm.StructureInfo.query.filter_by(facilityID=facilityID).all()
	G=nx.DiGraph()
	G.add_nodes_from([s.id for s in structures])
	for node in structures:
		G.node[node.id]['identifier'] = node.identifier
		G.node[node.id]['status'] = node.status
		for srvc in node.services:
				G.add_edge(node.id, srvc.id, {'structure_type': srvc.structure_type, 'status': srvc.status})

	node_colors = []
	edge_colors = []
	edge_styles = []
	for node, srvc, data in G.edges(data=True):
		# Edge Color
		if data['structure_type'] in ['WSR', 'WST']:
			color = 'blue'
		elif data['structure_type'] in ['P']:
			color = 'orange'
		elif data['structure_type'] in ['S']:
			color = 'gray'
		elif data['structure_type'] in ['C']:
			color = 'purple'
		elif data['structure_type'] in ['CST']:
			color = 'lightblue'
		else:
			color = 'black'
		edge_colors.append(color)

		# Edge Style
		if not data['status']:
			style='dashed'
		else:
			style='solid'
		edge_styles.append(style)

		# Node Color
		if not data['status']:
			color = 'red'
		else:
			color = 'green'
		node_colors.append(color)


	pos=nx.spring_layout(G)
	
	directory = os.path.join(app.config['FILE_FOLDER'], facilityID)
	if not os.path.exists(directory):
		os.makedirs(directory)
	G=nx.path_graph(4)
	nx.write_gexf(G, os.path.join(directory, 'facility_services_network.gexf'))


# To be depreciated for a js interative network
# This is depreciated in favor of sigma.js in the browser(templates)
@blueprint.after_request
def test(response):
	"""After every request in this blueprint the networkx models of the 
	facility must be redrawn to make sure they are accurate.
	"""
	facilityID = g.get('facilityID')
	_export_facility_network(facilityID)
	return response
'''


#  S E A R C H 
#------------
def _chart_structure_by_province(structure_type, disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	structures = sm.StructureInfo.query.filter_by(structure_type=structure_type).all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Structures by Province'
	chart.x_labels = [p.name for p in provinces]

	return {'title': chart.title, 'data': chart.render_data_uri()}

def _chart_percent_designation_by_province(disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	designations = fm.DesignationRef.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Designations by Province (%)'
	chart.value_formatter = lambda x: '{}%'.format(x)
	chart.x_labels = [p.name for p in provinces]
	for d in designations:
		chart.add(d.name, [(d.total_designations(p.id)/float(p.total_facilities))*100 if p.total_facilities > 0 else None for p in provinces])
	return {'title': chart.title, 'data': chart.render_data_uri()}

def _chart_facility_condition(disable_xml_declaration=False):
	facilities = fm.FacilityInfo.query.all()
	chart = pygal.Pie(style=pygal.style.BlueStyle)
	chart.title = 'Facility Status'
	chart.show_legend = False
	chart.add('Status', [{'value': len([f for f in facilities if f.status and not f.damaged]), 'label': 'Open', 'color': 'green'},
						{'value': len([f for f in facilities if not f.status and not f.damaged]), 'label': 'Closed', 'color': 'black'},
						{'value': len([f for f in facilities if f.status and f.damaged]), 'label': 'Open/Damaged', 'color': 'orange'},
						{'value': len([f for f in facilities if not f.status and f.damaged]), 'label': 'Closed/Damaged', 'color': 'red'}])
	return {'title': chart.title, 'data': chart.render_data_uri()}

def _chart_percent_facility_condition_by_province(disable_xml_declaration=False):
	provinces = fm.ProvinceInfo.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Facility Status by Province (%)'
	chart.value_formatter = lambda x: '{}%'.format(x)
	chart.show_legend = False
	chart.x_labels = [p.name for p in provinces]
	chart.add('', [{'value': p.facilities_open/float(len(p.facilities))*100, 'label': 'Open', 'color': 'green'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_closed/float(len(p.facilities))*100, 'label': 'Closed', 'color': 'black'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_damaged_open/float(len(p.facilities))*100, 'label': 'Damaged/Open', 'color': 'orange'} if p.total_facilities > 0 else None for p in provinces])
	chart.add('', [{'value': p.facilities_damaged_closed/float(len(p.facilities))*100, 'label': 'Damaged/Closed', 'color': 'red'} if p.total_facilities > 0 else None for p in provinces])
	return {'title': chart.title, 'data': chart.render_data_uri()}

def _chart_facility_rank():
	"""This is a test and not a complete ranking or report"""
	provinces = fm.ProvinceInfo.query.all()
	facilities = fm.FacilityInfo.query.all()
	chart = pygal.XY(style=pygal.style.BlueStyle)
	chart.stroke = False
	chart.title = 'Facility Condition'
	for f in facilities:
		chart.add(f.facilityName, [])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@blueprint.route('/data/charts')
@cache.cached(timeout=300, key_prefix=utils.make_cache_key)
def _charts():
	structure_type = request.args.get('structure_type')
	logger.debug('Enter _charts')
	chart1 = None#_chart_structure_by_province(structure_type)
	chart2 = _chart_percent_designation_by_province()
	chart3 = _chart_facility_condition()
	chart4 = _chart_percent_facility_condition_by_province()
	chart5 = _chart_facility_rank()
	logger.debug('Exit _charts')
	return jsonify({'charts': [chart1, chart2, chart3, chart4, chart5]})



# ===================== #
#  S T R U C T U R E S  #
# ===================== #

#  S E A R C H 
#------------
#@csrf_protect.exempt
@blueprint.route('/search/', methods=['GET', 'POST'])
@csrf_protect.exempt
def search():
	"""List structures."""
	logger.debug('Enter structure search')
	form = forms.StructureSearchForm()
	# Create the base query for the structures for all structures 
	# Create base queries for different columns of search page
	query = sm.StructureInfo.query.order_by(sm.StructureInfo.facilityID).order_by(sm.StructureInfo.structure_type).join(fm.FacilityInfo)
	type_query = None
	province_query = fm.ProvinceInfo.query.order_by(fm.ProvinceInfo.id)
	island_query = fm.IslandInfo.query.order_by(fm.IslandInfo.name)
	healthZone_query = fm.HealthZoneInfo.query.order_by(fm.HealthZoneInfo.name)
	designation_query = fm.DesignationRef.query.order_by(fm.DesignationRef.name)
	# Collect the argumetns from the Form's GET submit and set defaults to the form

	# Filter results
	#---------------

	# If structure_type filter main query
	structure_type = form.structure_type.data
	if structure_type != 'all':

		# Get the type tables for the selected structure_type
		if structure_type == 'B':
			structure_table = sm.BuildingInfo
			type_table = sm.BuildingRef
		elif structure_type == 'WSR':
			structure_table = sm.WaterSourceInfo
			type_table = sm.WaterSourceRef
		elif structure_type == 'WST':
			structure_table = sm.WaterStorageInfo
			type_table = sm.WaterStorageRef
		elif structure_type == 'P':
			structure_table = sm.PowerInfo
			type_table = sm.PowerRef
		elif structure_type == 'S':
			structure_table = sm.SanitationInfo
			type_table = sm.SanitationRef
		elif structure_type == 'C':
			structure_table = sm.CommunicationInfo
			type_table = sm.CommunicationRef
		elif structure_type == 'CST':
			structure_table = sm.ColdStorageInfo
			type_table = sm.ColdStorageRef
		elif structure_type == 'V':
			structure_table = sm.VehicleInfo
			type_table = sm.VehicleRef
		elif structure_type == 'BO':
			structure_table = sm.BoatInfo
			type_table = sm.BoatRef
		else:
			logger.error('Unknown structure_type: {0}'.format(structure_type))

		# Create the base query for the structures -- Overwrite query using StructureInfo before
		query = structure_table.query.order_by(structure_table.facilityID).join(fm.FacilityInfo)

		# Create query for all types that can populate type in the form
		type_query = type_table.query.order_by(type_table.type)

		# If a type is choosen add it to the filter on base query
		if form.typeID.data >= 0:
			query = query.join(type_table).filter(type_table.id==form.typeID.data)

	if form.provinceID.data >= 0:
		query = query.filter(fm.FacilityInfo.provinceID==form.provinceID.data)
		island_query = island_query.filter(fm.IslandInfo.provinceID==form.provinceID.data)
	if form.islandID.data >= 0:
		query = query.filter(fm.FacilityInfo.islandID==form.islandID.data)
	if form.healthZoneID.data >= 0:
		query = query.filter(fm.FacilityInfo.healthZoneID==form.healthZoneID.data)
	if form.designationID.data >= 0:
		query = query.filter(fm.FacilityInfo.designationID==form.designationID.data)

	# Finalize the queries and add an 'all' option to the SelectFields in the form
	form.structure_type.choices = [('all','all')] + [('B','Building'),('WSR','Water Source'),('WST','Water Storage'),('P','Power'),('S','Sanitation'),('C','Communication'),('CST','Cold Storage'),('V','Vehicle'),('BO','Boat')]
	if type_query:
		form.typeID.choices = [(-1,'all')] + [(t.id, t.type) for t in type_query.all()]
	else:
		del form.typeID
	form.provinceID.choices = [(-1,'all')] + [(p.id, p.name.strip()) for p in province_query.all()]

moha/templates/structures/form.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_datefield %}
    <form id="registerForm" class="form form-register" method="POST" action="" role="form" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>        

            {% for field in form %}
                {% if field.label.text == "CSRF Token" %}
                    {{ field }}
                
                {% elif field.widget.input_type == "hidden" %}
                    {{ field(class_="form-control") }}
                
                {% elif field.type == 'DateField' %}
                    {{ render_datefield(field) }}

                {% elif field.label.text == 'Status' %}
                    <div class="form-group">
                        {{ field.label }}
                        <br/>
                        <input {{ 'checked' if field.data == True else '' }} id="status" type="checkbox" data-toggle="toggle" data-on="Operational" data-off="Non-Operational" data-width="180" name="status" value="y"/>
                        <p class="help-block">{{ field.description }}</p>
                    </div>
                
                {% elif field.type == 'RadioField' %}
                    <div class='form-group'> 
                        {{ field.label }}
                        <br/>
                        <div class='btn-group' data-toggle='buttons'>
                            {% for r in field %}
                            <label class="btn btn-default {{ 'active' if r.checked else '' }}">
                                {{ r(type="radio")|safe }} {{ r.label }}
                            </label>
                            {% endfor %}
                        </div> 
                    </div>

                {% else %}
                    {{ render_field(field) }}
                {% endif %}
            {% else %}
                Error loading form. Please contact Application Administrator @ OGCIO
            {% endfor %}

            <p><input class="btn btn-primary btn-lg btn-submit btn-block" id="upload-button" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/structures/form_B.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_datefield %}
    <form id="registerForm" class="form form-register" method="POST" action="" role="form" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>        

            {{ form.facilityID }}

            <div class="row">
                <div class="col-sm-4">
                    {{ render_field(form.typeID) }}
                </div>

                <div class="col-sm-4">
                    {{ render_field(form.number) }}
                </div>

                <div class="col-sm-4">
                    {{ render_datefield(form.dateConstructed) }}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4">
                    {{ render_field(form.constructionID) }}
                </div>

                <div class="col-sm-4">
                    {{ render_field(form.area) }}
                </div>

                <div class="col-sm-4">
                    {{ render_field(form.roofID) }}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">
                    {{ render_field(form.description) }}
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        {{ form.status.label }}
                        <br/>
                        <input {{ 'checked' if form.status.data == True else '' }} id="status" type="checkbox" data-toggle="toggle" data-on="Operational" data-off="Non-Operational" data-width="180" name="status" value="y"/>
                        <p class="help-block">{{ form.status.description }}</p>
                    </div>
                </div>
            </div>

            <hr/>

            <p><input class="btn btn-primary btn-lg btn-submit btn-block" id="upload-button" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/structures/form_BO_inspection.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_inline_row, render_datefield %}
    <form id="InspectionForm" class="form form-register" method="POST" action="" role="form">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

        {{ form.structureID }}

        <div class="row">
            <div class="col-sm-6">
                {{ render_datefield(form.inspectionDate) }}
            </div>
            <div class="col-sm-6">
                {{ render_field(form.inspectorName) }}         
            </div>
        </div>

        {{ render_inline_row(form.engineCond, form.engineNote)}}
        {{ render_inline_row(form.hullCond, form.hullNote)}}

        <p><input class="btn btn-primary btn-lg btn-submit btn-block" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/structures/form_B_inspection.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_inline_row, render_datefield %}
    <form id="InspectionForm" class="form form-register" method="POST" action="" role="form">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

        {{ form.structureID }}

        <div class="row">
            <div class="col-sm-6">
                {{ render_datefield(form.inspectionDate) }}
            </div>
            <div class="col-sm-6">
                {{ render_field(form.inspectorName) }}         
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-6">
                {{ render_field(form.cycloneTies) }}
            </div>
            <div class="col-sm-6">
                {{ render_field(form.cycloneScrews) }}
            </div>
        </div>


        {{ render_field(form.visibleSub) }}
        
        <div id="substructure">
        {{ render_inline_row(form.subCond, form.subNote) }}
        </div>
        {{ render_inline_row(form.inWallCond, form.inWallNote) }}


        {{ render_inline_row(form.exWallCond, form.exWallNote)}}
        {{ render_inline_row(form.windowCond, form.windowNote)}}
        {{ render_inline_row(form.shutterCond, form.shutterNote)}}
        {{ render_inline_row(form.inDoorCond, form.inDoorNote)}}
        {{ render_inline_row(form.exDoorCond, form.exDoorNote)}}
        {{ render_inline_row(form.floorCond, form.floorNote)}}
        {{ render_inline_row(form.verandahCond, form.verandahNote)}}
        {{ render_inline_row(form.roofCond, form.roofNote)}}
        {{ render_inline_row(form.roofFrameCond, form.roofFrameNote)}}
        {{ render_inline_row(form.ceilingCond, form.ceilingNote)}}
        {{ render_inline_row(form.fasciaCond, form.fasciaNote)}}
        {{ render_inline_row(form.gutterCond, form.gutterNote)}}
        {{ render_inline_row(form.columnCond, form.columnNote) }}
        {{ render_inline_row(form.beamCond, form.beamNote) }}
        {{ render_inline_row(form.electricalCond, form.electricalNote) }}
        {{ render_inline_row(form.plumbingCond, form.plumbingNote) }}

        <p><input class="btn btn-primary btn-lg btn-submit btn-block" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
<script>
$('#visibleSub').on('change', function() {
  if ( this.value == 'True')
  {
    $("#substructure").show();
  }
  else
  {
    $("#substructure").hide();
  }
});
</script>
{% endblock %}

moha/templates/structures/form_V_inspection.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_inline_row, render_datefield %}
    <form id="InspectionForm" class="form form-register" method="POST" action="" role="form">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

        {{ form.structureID }}

        <div class="row">
            <div class="col-sm-6">
                {{ render_datefield(form.inspectionDate) }}
            </div>
            <div class="col-sm-6">
                {{ render_field(form.inspectorName) }}         
            </div>
        </div>

        {{ render_inline_row(form.exteriorCond, form.exteriorNote)}}
        {{ render_inline_row(form.interiorCond, form.interiorNote)}}
        {{ render_inline_row(form.lightsCond, form.lightsNote)}}
        {{ render_inline_row(form.brakeCond, form.brakeNote)}}
        {{ render_inline_row(form.steeringCond, form.steeringNote)}}
        {{ render_inline_row(form.suspensionCond, form.suspensionNote)}}
        {{ render_inline_row(form.exhaustCond, form.exhaustNote)}}
        {{ render_inline_row(form.tyresCond, form.tyresNote)}}
        {{ render_inline_row(form.fuelSystemCond, form.fuelSystemNote)}}

        {{ render_field(form.mileage) }}

        <p><input class="btn btn-primary btn-lg btn-submit btn-block" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/structures/form_file.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
  <h1>{{ title }}</h1>
{% else %}
  <h1>File</h1>
{% endif %}
	<br/>
	{% from "_formhelpers.html" import render_datefield %}
	<form id="registerForm" class="form form-register" method="POST" action="" role="form" enctype="multipart/form-data">
			<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>        

			{% if form.inspectionID %}
			<div class="form-group">
				{{ form.inspectionID.label }} {% if form.file.flags.required %}*{% endif %}
				{{ form.inspectionID(class_="form-control") }}
				<p class="help-block">{{ form.inspectionID.description }}</p>
			</div>
			{% endif %}

			<div class="form-group">
				{{ form.file.label }} {% if form.file.flags.required %}*{% endif %}
				{{ form.file(class_="form-control") }}
				<p class="help-block">{{ form.file.description }}</p>
			</div>

			<div class="form-group">
				{{ render_datefield(form.dateCreated) }}
			</div>

			<div class="form-group">
				{{ form.description.label }} {% if form.description.flags.required %}*{% endif %}
				{{ form.description(class_="form-control") }}
			</div>

			{% if default %}
			<div class="form-group">
				<input type="checkbox" data-toggle="toggle" data-on="Default" data-off="Not Default" name="default" value="default"/>
			</div>
			{% endif %}
			
			<p><input class="btn btn-primary btn-lg btn-submit btn-block" id="upload-button" type="submit" value="Submit"></p>
	</form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/structures/structures.html
{% extends "layout.html" %}

{% block content %}
<div class="body-content">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <div class='btn-toolbar pull-right'>
            <div class='btn-group'>
              <button class="btn btn-default" data-toggle="collapse" href="#graphs"><i class="fa fa-bar-chart"></i> Graphs</button>
              <button class="btn btn-default dropdown-toggle btn-large" data-toggle="dropdown"><i class="fa fa-cogs"></i> Options <i class="fa fa-caret-down"></i></button>
              <ul class="dropdown-menu pull-right">
                <li><a href="#"><i class="fa fa-download"></i> Download Excel</a></li>
              </ul>     
            </div>
        </div>
        Structures
      </h1>
    </div>
  </div>

  <script>

    $.getJSON("{{ url_for('structure._charts') }}", {structure_type: "{{form.structure_type.data}}"}, function(data) {
      $('#graphs').find('#chart-navigation').empty();
      $.each(data.charts, function(i, chart) {
        var $nav = $('<li>').append(
          $('<a href="#" data-toggle="tab">').text(chart.title).attr('href', '#chart-' + i)
          );
        var $chart = $('<div>', {'class': 'tab-pane', 'id': ""}).append(
          $('<embed>', {'style': "width:100%;height:75vh;", 'type': "image/svg+xml"})
          );
        var $chart = $chart.attr('id', 'chart-' + i);
        $('#graphs').find('#chart-navigation').append($nav);
        $('#graphs').find('#chart-div').append($chart);
        $('#chart-' + i).find('embed').attr('src', chart.data);
      });
      makeActive();
    });
      
    function makeActive() {
      $("#chart-navigation li:first").addClass("active");
      $("#chart-div div:first").addClass("active");
    };
  </script>

  <div class="row collapse graphTabs" id="graphs">
    <ul class="nav nav-pills" id="chart-navigation">
    </ul>

    <div class="tab-content clearfix" id="chart-div">
    </div>
  </div>

  <div class="row">
  {{ pagination.info }}
    <table class="table table-condensed">
      <thead>
        <tr style="font-size:1.4em;font-weight:700;">
          <th>#</th>
          <th>Structure</th>
          <th>Type</th>
          <th>Facility</th>
          <th>Desigination</th>
          <th>Island</th>
          <th>Heath Zone</th>
          <th>Province</th>
        </tr>
        <tr>
          <form action="{{ url_for('structure.search') }}" method="POST">
            {{ form.hidden_tag() }}
            <th></th>
            <th>
              <div class="form-group">
                {{ form.structure_type(class_="form-control") }}
              </div>
            </th>
            <th>
            {% if form.typeID %}
              <div class="form-group">
                {{ form.typeID(class_="form-control") }}
              </div>
            {% endif %}
            </th>
            <th></th>
            <th>
              <div class="form-group">
                {{ form.designationID(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.islandID(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.healthZoneID(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                {{ form.provinceID(class_="form-control") }}
              </div>
            </th>
            <th>
              <div class="form-group">
                <button class="btn btn-default btn-block" type="submit" value="submit"><i class="fa fa-refresh"></i></button>
              </div>
            </th>
          </form>
        </tr>
      </thead>
      <tbody class="rowlink" data-link="row">
    	{% for structure in structures %}
        <tr>
          <td><a href="{{ url_for('facility.facility', facilityID=structure.facilityID) }}"></a>{{ loop.index + (pagination.page - 1) * pagination.per_page }}</td>
          <td>{{ structure.structure_type }}</td>
          <td>{{ structure.type }}</td>
          <td>{{ structure.facility.facilityName }}</td>
          <td>{{ structure.facility.designation.name }}</td>
          <td>{{ structure.facility.island.name }}</td>
          <td>{{ structure.facility.healthZone }}</td>
          <td>{{ structure.facility.province.name }}</td>
        </tr>
    	{% endfor %}
      </tbody>
    </table>
    {{ pagination.links }} 
  </div>
</div>
{% endblock %}