moha/personnel/forms.py
# -*- coding: utf-8 -*-
"""Personnel Forms"""
import datetime

from flask import request
from flask_wtf import Form
from wtforms import StringField, SelectField, IntegerField, DateField, BooleanField, TextAreaField, HiddenField, SubmitField
from wtforms.validators import DataRequired

from flask import current_app as app

from moha.public.forms import RedirectForm


class PositionForm(RedirectForm):
	"""Position Form"""

	pcv = SelectField('PCV',
						choices=[('P', 'P'),('C', 'C'),('V', 'V')],
						validators=[DataRequired()])

	pn = IntegerField('PN')
	
	fund = IntegerField('Fund')

	costCenterCode = StringField('Cost Centre Code')

	costCenterName = StringField('Cost Centre Name')

	activity = StringField('Activity')

	department = StringField('Department')

	jobCode = StringField('Job Code')

	salaryGrade = StringField('Salary Grade')

	facilityID = HiddenField('Facility ID')

	titleID = SelectField('Position Title',
							choices=[],
							coerce=int,
							validators=[DataRequired()])


	def validate(self):
		"""Validate the form."""
		initial_validation = super(PositionForm, self).validate()
		if not initial_validation:
			return False

		return True


class PersonnelForm(RedirectForm):
	"""Personnel Form"""
	
	vnpfNumber = StringField('VNPF Number')
	name = StringField('Name', validators=[DataRequired()])

	def validate(self):
		"""Validate the form."""
		initial_validation = super(PersonnelForm, self).validate()
		if not initial_validation:
			return False

		return True


class PlacementForm(RedirectForm):
	"""Placement Form"""

	positionID = SelectField('Position Selection',
							choices=[],
							coerce=int,
							validators=[DataRequired()])

	personnelID = SelectField('Personnel Selection',
							choices=[],
							coerce=int,
							validators=[DataRequired()])


	def validate(self):
		"""Validate the form."""
		initial_validation = super(PlacementForm, self).validate()
		if not initial_validation:
			return False

		return True


class PositionSearchForm(Form):
	"""Search Personnel List."""

	pn = StringField('PN')
	vnpf = StringField('VNPF')
	title = SelectField('Title', choices=[], coerce=int)
	pcv = SelectField('PCV', choices=[])
	jobCode = StringField('Job Code')
	facility = SelectField('Facility', choices=[])
	province = SelectField('Province', choices=[], coerce=int)

	def validate(self):
		"""Validate the form."""
		initial_validation = super(PositionSearchForm, self).validate()
		if not initial_validation:
			return False

		return True

moha/map/__init__.py
# -*- coding: utf-8 -*-
"""The map module."""
from . import views  # noqa

moha/personnel/__init__.py
# -*- coding: utf-8 -*-
"""The Personel module."""
from . import views  # noqa

moha/personnel/views.py
# -*- coding: utf-8 -*-
"""Personel section."""
from flask import Blueprint, flash, redirect, render_template, request, url_for, send_from_directory, jsonify
from flask_login import login_required
from flask_paginate import Pagination, get_page_parameter, get_per_page_parameter
from sqlalchemy.orm.exc import NoResultFound

from . import forms
from . import models as pm
from moha.facility import models as fm

# I know this is bad but I have to import moha directly to access cache_utils.
# Importing cache_utils as I did in other views does not work here.
# It is a mystery.
# Time is not available to me so I'm doing it this way.
import moha 
from moha import utils

import pygal
import structlog
logger = structlog.getLogger(__name__)

blueprint = Blueprint('personnel', __name__, url_prefix='/personnel', static_folder='../static')


@blueprint.route('/')
def search():
	logger.debug('Enter search personnels')
	form = forms.PositionSearchForm()
	# Create the base query for the facilities
	query = pm.PositionInfo.query
	# Create base queries for different columns of search page
	title_query = pm.TitleRef.query.order_by(pm.TitleRef.id)
	facility_query = fm.FacilityInfo.query.order_by(fm.FacilityInfo.facilityID)
	province_query = fm.ProvinceInfo.query.order_by(fm.ProvinceInfo.id)
	# Collect the arguments from the Form's GET submit and set defaults
	try:
		provinceID = int(request.args.get('province'))
		form.province.default = provinceID
		if provinceID and provinceID >= 0:
			query = query.join(fm.FacilityInfo)
			query = query.filter(fm.FacilityInfo.provinceID==provinceID)
	except TypeError:
		pass
	try:
		pn = request.args.get('pn')
		form.pn.default = pn
		if pn:
			query = query.filter(pm.PositionInfo.pn.contains(pn))
	except TypeError:
		pass
	try:
		vnpf = request.args.get('vnpf')
		form.vnpf.default = vnpf
		if vnpf:
			query = query.join(pm.PersonnelInfo).filter(pm.PersonnelInfo.vnpfNumber.contains(vnpf))
	except TypeError:
		pass
	try:
		pcv = request.args.get('pcv')
		form.pcv.default = pcv
		if pcv and pcv != 'all':
			query = query.filter(pm.PositionInfo.pcv==pcv)
	except TypeError:
		pass
	try:
		# Set defaults on form so that between page refreshes the selected variables remain
		titleID = int(request.args.get('title'))
		form.title.default = titleID
		if titleID and titleID >= 0:
			query = query.filter(pm.PositionInfo.titleID==titleID)
	except TypeError:
		pass
	try:
		jobCode = request.args.get('jobCode')
		form.jobCode.default = jobCode
		if jobCode:
			query = query.filter(pm.PositionInfo.jobCode.contains(jobCode))
	except TypeError:
		pass
	try:
		facilityID = int(request.args.get('facility'))
		form.facility.default = facilityID
		if facilityID and facilityID >= 0:
			query = query.filter(pm.PositionInfo.facilityID==facilityID)
	except TypeError:
		pass
	# Finalize the queries and add an 'all' option to the SelectFields in the form
	form.title.choices = [(-1,'all')] + [(t.id, t.type.strip()) for t in title_query.all()]
	form.pcv.choices = [('all','all')] + [('P', 'P'),('C', 'C'),('V', 'V')]
	form.facility.choices = [(-1,'all')] + [(f.facilityID, f.identifier) for f in facility_query.all()]
	form.province.choices = [(-1,'all')] + [(p.id, p.name) for p in province_query.all()]
	form.process()  # We have to call this to 're-build' the form with our new choices and defaults selected
	# Make pagination 
	page = request.args.get(get_page_parameter(), type=int, default=1)
	per_page = request.args.get(get_per_page_parameter(), type=int, default=10)
	positions = query.order_by(pm.PositionInfo.id)
	pagination = Pagination(page=page, per_page=per_page, total=positions.count(), search=False, record_name='positions', bs_version=3)
	positions = positions.limit(per_page).offset((pagination.page - 1) * per_page)
	return render_template('personnels/search.html', form=form, positions=positions, pagination=pagination)#, charts=_charts())



# ============= #
#  C H A R T S  #
# ============= #

# unknown use for now but demo of radar c
def _chart_personnel_and_positions():
	titles = pm.TitleRef.query.all()
	personnel = pm.PersonnelInfo.query.all()
	chart = pygal.Radar(style=pygal.style.Style(colors=('red','blue'), opacity=.4, opacity_hover=.7))
	chart.title = 'Personnel by Title and Positions by Title'
	chart.x_labels = [title.type for title in titles]
	chart.add('Positions', [t.total_positions for t in titles], fill=True, stroke_style={'width': 5, 'dasharray': '3, 6'})
	chart.add('Personnel', [t.total_personnel for t in titles], fill=True)
	return chart.render_data_uri()


#  I N D E X
#----------
def _chart_vacancy_by_province():
	provinces = fm.ProvinceInfo.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Vacancy by Province'
	chart.x_labels = [p.name for p in provinces] + ['Unknown']
	chart.add('Filled', [p.total_positions_filled for p in provinces] + [pm.PositionInfo.query.filter_by(facilityID=None).filter(pm.PositionInfo.personnelID != None).count()])
	chart.add('Unfilled', [p.total_positions_unfilled for p in provinces] + [pm.PositionInfo.query.filter_by(facilityID=None).filter_by(personnelID=None).count()])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@blueprint.route('/data/charts')
#@cache.cached(timeout=300, key_prefix=utils.make_cache_key)
def _charts():
	"""Display charts on index view of personnel"""
	chart1 = _chart_vacancy_by_province()
	return jsonify({'charts': [chart1]})


# ========================== #
#  S P E C I A L  V I E W S  #
# ========================== #

#  C A D R E
#----------
def _chart_percent_cadre_by_province(cadre):
	titles = pm.TitleRef.query.filter_by(cadreID=cadre.cadreID).all()
	provinces = fm.ProvinceInfo.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = 'Position Titles of {0} Cadre by Province (%)'.format(cadre.type)
	chart.x_labels = [p.name for p in provinces] + ['Unknown']
	for t in titles:
		try:
			unknown_province = (pm.PositionInfo.query.filter(pm.PositionInfo.facilityID==None).filter_by(titleID=t.id).count() / float(pm.PositionInfo.query.filter(pm.PositionInfo.titleID.in_(cadre.cadre_title_ids)).filter(pm.PositionInfo.facilityID==None).count()) )*100
		except ZeroDivisionError:
			unknown_province = 0
		known_provinces = [( t.total_by_province(p.id) / float(p.total_positions_of_cadre(cadre.cadreID)) )*100 if p.total_positions_of_cadre(cadre.cadreID) > 0 else None for p in provinces]
		chart.add(t.type, known_provinces + [unknown_province])
	return {'title': chart.title, 'data': chart.render_data_uri()}

def _chart_titles_by_cadre(cadre):
	chart = pygal.Pie(style=pygal.style.BlueStyle)
	chart.title = 'Position Titles of {0} Cadre'.format(cadre.type)
	#chart.x_labels = [t.type for t in cadre.titles]
	chart.add('Titles', [len(t.positions) for t in cadre.titles])
	return {'title': chart.title, 'data': chart.render_data_uri()}

@blueprint.route('/data/cadre')
#@cache.cached(timeout=300, key_prefix=utils.make_cache_key)
def data_cadre():
	cadreID = request.args.get('cadreID')
	cadre = pm.CadreRef.query.filter_by(cadreID=cadreID).one()
	chart1 = _chart_titles_by_cadre(cadre)
	chart2 = _chart_percent_cadre_by_province(cadre)
	charts = [chart1, chart2]
	return jsonify({'charts': charts})


#  P O S I T I O N S
#------------------
def _chart_title_positions_by_province(positions):
	if not positions:
		return ''  # return generic no data graph?
	provinces = fm.ProvinceInfo.query.all()
	chart = pygal.StackedBar(style=pygal.style.BlueStyle)
	chart.title = '{0} Positions by Province'.format(positions[0].title.type)
	chart.x_labels = [p.name for p in provinces] + ['Unknown']
	filled_positions = []
	unfilled_positions = []
	for province in provinces:
		# much faster than calling sqlalchemy again and using .count()
		filled_positions.append(len([p for p in positions if p.facility and p.facility.provinceID==province.id and p.personnelID]))
		unfilled_positions.append(len([p for p in positions if p.facility and p.facility.provinceID==province.id and not p.personnelID]))
	filled_positions.append(len([p for p in positions if not p.facility and p.personnelID]))
	unfilled_positions.append(len([p for p in positions if not p.facility and not p.personnelID]))
	chart.add('Filled', filled_positions)
	chart.add('Unfilled', unfilled_positions)
	return chart.render_data_uri()


@blueprint.route('/data/positions')
#@cache.cached(timeout=300, key_prefix=utils.make_cache_key)
def data_positions():
	titleID = request.args.get('titleID')
	positions = pm.PositionInfo.query.filter_by(titleID=titleID).all()
	addButton = """<!--Find this HTML in personnel/views.py--><a class="btn btn-default btn-sm" type="button" href="{0}"><i class="fa fa-{1}"></i> <i class="fa fa-plus"></i></a>"""
	#delButton = """<a class="btn btn-danger btn-sm {2}" type="button" href="#" data-href="{0}" data-toggle="confirmation" ><i class="fa fa-{1}"></i> <i class="fa fa-minus"></i></a>"""
	data = []
	for p in positions:
		if p.title:
			cadre = dict(cadreID=p.title.cadreID,type=p.title.cadre.type)
			title = dict(titleID=p.titleID,type=p.title.type,clinical=p.title.clinical,cadre=cadre)
		else:
			title={}
		if p.facility:
			facility = dict(facilityID=p.facility.facilityID,identifier=p.facility.identifier,link='<a href="{0}">{1}</a>'.format(url_for('facility.facility', facilityID=p.facilityID), p.facility.identifier))
		else:
			facility = {}
		if p.personnel:
			personnel = dict(personnelID=p.personnelID,identifier=p.personnel.identifier,link='<a href="{0}">{1}</a>'.format(url_for('personnel.view_personnel', personnelID=p.personnel.id), p.personnel.identifier))
		else:
			personnel = {}
		addButton=addButton.format(url_for('personnel.add_placement', positionID=p.id), 'user-md' if p.title.clinical else 'user')
		#delButton=delButton.format(url_for('personnel.delete_placement', positionID=p.id), 'user-md' if p.title.clinical else 'user', 'disabled' if not p.personnel else '')
		data.append(dict(id=p.id,
						 pn=p.pn,
						 pcv=p.pcv,

moha/templates/personnels/form.html
{% extends "layout.html" %}

{% block content %}
<div class="container-narrow">
{% if title %}
    <h1>{{ title }}</h1>
{% else %}
    <h1></h1>
{% endif %}
    <br/>
    {% from "_formhelpers.html" import render_field, render_datefield %}
    <form id="registerForm" class="form form-register" method="POST" action="" role="form" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>        

            {% for field in form %}
                {% if field.label.text == "CSRF Token" %}
                    {{ field }}
                
                {% elif field.widget.input_type == "hidden" %}
                    {{ field(class_="form-control") }}
                
                {% elif field.type == 'DateField' %}
                    {{ render_datefield(field) }}
                
                {% elif field.type == 'RadioField' %}
                    <div class='form-group'> 
                        {{ field.label }}
                        <br/>
                        <div class='btn-group' data-toggle='buttons'>
                            {% for r in field %}
                            <label class="btn btn-default {{ 'active' if r.checked else '' }}">
                                {{ r(type="radio")|safe }} {{ r.data }}
                            </label>
                            {% endfor %}
                        </div> 
                    </div>

                {% else %}
                    {{ render_field(field) }}
                {% endif %}
            {% else %}
                Error loading form. Please contact Application Administrator @ OGCIO
            {% endfor %}

            <p><input class="btn btn-primary btn-lg btn-submit btn-block" id="upload-button" type="submit" value="Submit"></p>
    </form>
</div>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker3.min.css') }}" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
<script>
$('.datepicker').datepicker();
</script>
{% endblock %}

moha/templates/personnels/personnel_layout.html
{% extends "layout.html" %}

{% block css %}{% endblock %}

{% block content %}
<div class="body-content">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        <div class='btn-toolbar pull-right'>
            <div class='btn-group'>      
              <button class="btn btn-default" data-toggle="collapse" href="#graphs"><i class="fa fa-bar-chart"></i> Graphs</button>
              <button class="btn btn-default dropdown-toggle btn-large" data-toggle="dropdown"><i class="fa fa-cogs"></i> Options <i class="fa fa-caret-down"></i></button>
              <ul class="dropdown-menu pull-right">
                <li><a href="{{ url_for('personnel.add_personnel') }}">Add Personnel</a></li>
                <li><a href="{{ url_for('personnel.upload_excel') }}"><i class="fa fa-file-excel-o"></i> Upload Excel</a></li>
              </ul>     
            </div>
        </div>
        Personnel
      </h1>
    </div>
  </div>

  <script>
    $.getJSON("{{ url_for('personnel._charts') }}", function(data) {
      $('#graphs').find('#chart-navigation').empty();
      $.each(data.charts, function(i, chart) {
        var $nav = $('<li>').append(
          $('<a href="#" data-toggle="tab">').text(chart.title).attr('href', '#chart-' + i)
          );
        var $chart = $('<div>', {'class': 'tab-pane', 'id': ""}).append(
          $('<embed>', {'style': "width:100%;height:75vh;", 'type': "image/svg+xml"})
          );
        var $chart = $chart.attr('id', 'chart-' + i);
        $('#graphs').find('#chart-navigation').append($nav);
        $('#graphs').find('#chart-div').append($chart);
        $('#chart-' + i).find('embed').attr('src', chart.data);
      });
      makeActive();
    });

    function makeActive() {
      $("#chart-navigation li:first").addClass("active");
      $("#chart-div div:first").addClass("active");
    };
  </script>

  <div class="row collapse graphTabs" id="graphs">
    <ul class="nav nav-pills" id="chart-navigation">
    </ul>

    <div class="tab-content clearfix" id="chart-div">
    </div>
  </div>

  {% block personnel_content %}{% endblock %}

</div>
{% endblock %}

moha/templates/personnels/search.html
{% extends "personnels/personnel_layout.html" %}

{% block personnel_content %}
<div class="row">
  {{ pagination.info }}
  <table class="table table-hover table-condensed sortable">
    <thead>
      <tr style="font-size:1.4em;font-weight:700;">
        <th>#</th>
        <th class="col-xs-1">PN</th>
        <th class="col-xs-1">VNPF</th>
        <th class="col-xs-2">Name</th>
        <th class="col-xs-1">PCV</th>
        <th class="col-xs-3">Position Title</th>
        <th class="col-xs-1">Job Code</th>
        <th class="col-xs-2">Facility</th>
        <th class="col-xs-1">Province</th>
        <th></th>
      </tr>
      <tr>
        <form id="table-search-form" action="{{ url_for('personnel.search') }}" method="GET">
          <th></th>
          <th>
            <div class="form-group">
              {{ form.pn(class_="form-control") }}
            </div>
          </th>
          <th>
            <div class="form-group">
              {{ form.vnpf(class_="form-control") }}
            </div>
          </th>
          <th></th>
          <th>
            <div class="form-group">
              {{ form.pcv(class_="form-control") }}
            </div>
          </th>
          <th>
            <div class="form-group">
              {{ form.title(class_="form-control") }}
            </div> 
          </th>
          <th>
            <div class="form-group">
              {{ form.jobCode(class_="form-control") }}
            </div>
          </th>
          <th>
            <div class="form-group">
              {{ form.facility(class_="form-control") }}
            </div>
          </th>
          <th>
            <div class="form-group">
              {{ form.province(class_="form-control") }}
            </div>
          </th>
          <th>
            <div class="form-group">
              <button class="btn btn-default btn-block" type="submit" value="submit"><i class="fa fa-refresh"></i></button>
            </div>
          </th>
        </form>
      </tr>
    </thead>
    <tbody>
  	{% for position in positions %}
      <tr>
        <td>{{ loop.index + (pagination.page - 1) * pagination.per_page }}</td>
        <td>{{ position.pn }}</td>
      {% if position.personnel.employed %}
        <td>{{ position.personnel.vnpfNumber }}</td>
        <td><a href="{{ url_for('personnel.view_personnel', personnelID=position.personnel.id) }}">{{ position.personnel.name }}</a></td>
      {% else %}
        <td></td>
        <td></td>
      {% endif %}
        <td>{{ position.pcv }}</td>
        <td>{{ position.title.type }}</td>
        <td>{{ position.jobCode }}</td>
        {% if position.facility %}
        <td><a href="{{ url_for('facility.facility', facilityID=position.facility.facilityID) }}">{{ position.facility.identifier }}</a></td>
        <td>{{ position.facility.province.name }}</td>
        {% else %}
        <td></td>
        <td></td>
        {% endif %}
      </tr>
  	{% endfor %}
    </tbody>
  </table>    
  {{ pagination.links }}
</div>
{% endblock %}

moha/templates/personnels/sort_cadre.html
{% extends "personnels/personnel_layout.html" %}

{% block css %}
<style>
/* Graphs */
a:hover, a:visited, a:link, a:active {
	text-decoration: none;
}

.controls {
	margin-bottom: 10px;
}

.collapse-group {
	padding: 10px;
	margin-bottom: 10px;
}

.panel-title .trigger:before {
	content: '\e082';
	font-family: 'Glyphicons Halflings';
	vertical-align: text-bottom;
}

.panel-title .trigger.collapsed:before {
	content: '\e081';
}
</style>

<style>
#graphTabs .nav-pills > li > a {
	border-radius: 4px 4px 0 0 ;
}

#graphTabs .tab-content {
	color : white;
	background-color: #428bca;
	padding : 5px 15px;
}

/* Tree */
.tree {
    min-height:20px;
    padding:19px;
    margin-bottom:20px;
    background-color:#fbfbfb;
    border:1px solid #999;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
    border-radius:4px;
    -webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05);
    -moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05);
    box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05)
}
.tree li {
    list-style-type:none;
    margin:0;
    padding:10px 5px 0 5px;
    position:relative
}
.tree li::before, .tree li::after {
    content:'';
    left:-20px;
    position:absolute;
    right:auto
}
.tree li::before {
    border-left:1px solid #999;
    bottom:50px;
    height:100%;
    top:0;
    width:1px
}
.tree li::after {
    border-top:1px solid #999;
    height:20px;
    top:25px;
    width:25px
}
.tree li span {
    -moz-border-radius:5px;
    -webkit-border-radius:5px;
    border:1px solid #999;
    border-radius:5px;
    display:inline-block;
    padding:3px 8px;
    text-decoration:none
}
.tree li.parent_li>span {
    cursor:pointer
}
.tree>ul>li::before, .tree>ul>li::after {
    border:0
}
.tree li:last-child::before {
    height:30px
}
.tree li.parent_li>span:hover, .tree li.parent_li>span:hover+ul li span {
    background:#eee;
    border:1px solid #94a0b4;
    color:#000
}
</style>
{% endblock %}

{% block personnel_content %}
<div class="tree well">
	<ul>
		{% for cadre in [cadre_root] recursive %}
		<li>
			<span><i class="icon-calendar"></i> {{ cadre }}</span> &ndash; <a href="#" data-id="{{ cadre.cadreID }}" data-name="{{ cadre.type }}" data-toggle="modal" data-target="#cadreModal">View Cadre</a>
			{% if cadre.children %}
			<ul>
				{{ loop(cadre.children) }}
			</ul>
			{% endif %}
			{% if cadre.titles %}
			<ul>
				{% for title in cadre.titles %}
				<li>
					<span class="badge badge-info"><i class="icon-minus-sign"></i> {{ title }}</span> &ndash; <a href="#" data-id="{{ title.id }}" data-name="{{ title.type }}" data-toggle="modal" data-target="#positionsModal"">View Positions</a>
				</li>
				{% endfor %}
			</ul>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
</div>

<div class="modal fade" id="cadreModal" role="dialog">
	<div class="modal-dialog">

	  <!-- Modal content-->
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal">&times;</button>
	      <h4 class="modal-title" id="cadreTitle">Cadre</h4>
	    </div>
	    <div class="modal-body">
	    </div>
	    <div class="modal-footer">
	      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	    </div>
	  </div>

	</div>
</div>

<div class="modal fade" id="positionsModal" role="dialog">
	<div class="modal-dialog">

	  <!-- Modal content-->
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal">&times;</button>
	      <h4 class="modal-title" id="positionTitle">Position Title</h4>
	    </div>
	    <div id="modaladdpay" class="modal-body">
				<embed id="positionsModalChart" style="width:100%;height:75vh;" type="image/svg+xml" src=""/>
	      <table class="table table-condensed table-hover" id="positionsModalTable">
	      	<thead>
	      		<tr>
	      			<th>PN</th>
	      			<th>Job Code</th>
	      			<th>PCV</th>
	      			<th>Facility</th>
	      			<th>Personnel</th>
	      		</tr>
	      	</thead>
	      	<tbody>
	      	</tbody>
	      </table>
	    </div>
	    <div class="modal-footer">
	      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	    </div>
	  </div>

	</div>
</div>

{% endblock %}

{% block js %}
<script>
$('#positionsModal').on('show.bs.modal', function(e) {  
	var titleID = $(e.relatedTarget).data('id')
	var titleName = $(e.relatedTarget).data('name')
	$("#positionsModalTable").find('tbody').empty();
	// perhaps add loading gif here
	$("#positionTitle").text(titleName);
	$.getJSON("{{ url_for('personnel.data_positions') }}", {titleID: titleID}, function(data) {
		$.each(data.data, function(i, item) {
			var $tr = $('<tr>').append(
				$('<td>').text(item.pn),
				$('<td>').text(item.jobCode),
				$('<td>').text(item.pcv),
				$('<td>').html(item.facility.link),
				$('<td>').html(item.personnel.link),
				$('<td>').html(item.buttons),
			);
			$("#positionsModalTable").find('tbody').append($tr);
			$("#positionsModalChart").attr("src", data.chart);
		});
	});
	$('#positionsModal').animate({ scrollTop: 0 }, 'slow');
});

$('#cadreModal').on('show.bs.modal', function(e) {  
	var cadreID = $(e.relatedTarget).data('id')
	var cadreName = $(e.relatedTarget).data('name')
	$("#cadreModal").find(".modal-body").empty();
	// Perhaps add a loading gif here
	$("#cadreTitle").text("Cadre: " + cadreName);
	$.getJSON("{{ url_for('personnel.data_cadre') }}", {cadreID: cadreID}, function(data) {
		$.each(data.charts, function(i, chart) {
			var $embed = $('<embed>', {
				'id': 'cadreModal-chart-' + i,
				'style': 'width:100%;height:75vh;',
				'type': 'image/svg+xml',
				'src': chart.data,
			});
			$("#cadreModal").find(".modal-body").append($embed);
		})
	});
	$('#cadreModal').animate({ scrollTop: 0 }, 'slow');
});

$(function () {
    $('.tree li:has(ul)').addClass('parent_li').find(' > span').attr('title', 'Collapse this branch');
    $('.tree li.parent_li > span').on('click', function (e) {
        var children = $(this).parent('li.parent_li').find(' > ul > li');
        if (children.is(":visible")) {
            children.hide('medium');
            $(this).attr('title', 'Expand this branch').find(' > i').addClass('icon-plus-sign').removeClass('icon-minus-sign');
        } else {
            children.show('medium');
            $(this).attr('title', 'Collapse this branch').find(' > i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
        }
        e.stopPropagation();
    });
});
</script>
{% endblock %}